name: Docker Image CI

on: [push]


jobs:

  build:

    runs-on: [self-hosted, linux, ARM64]

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        echo ${GITHUB_ACTOR}
        echo ${GITHUB_REPOSITORY}
        # docker build . --file Dockerfile-rpi --tag frigate-rpi:$(date +%s)
