name: Docker Image CI

on: [push]


jobs:

  build:

    runs-on: [self-hosted, linux, ARM64]

    steps:
      - uses: actions/checkout@v1
      - name: Echo env vars
        run: echo ${GITHUB_ACTOR}
      - name: Echo env vars
        run: echo ${GITHUB_REPOSITORY}
      - name: Echo env vars
        run: env
      - name: Build the Docker image
        run: docker build . --file Dockerfile-rpi --tag frigate-rpi:$(date +%s)
