name: Docker Image CI

on: [push]


jobs:

  build:

    runs-on: [self-hosted, linux, ARM64]

    steps:
      - uses: actions/checkout@v1
      - name: Echo env vars
        run: echo ${GITHUB_ACTOR}
      - name: Echo env vars
        run: echo ${GITHUB_REPOSITORY}
      - name: Echo env vars
        run: env
      - name: Build the Docker image
        run: docker build --file Dockerfile-rpi --tag docker.pkg.github.com/${GITHUB_REPOSITORY}/frigate-rpi:latest .
      - name: GitHub Packages login
        run: docker login docker.pkg.github.com -u ${GITHUB_ACTOR} -p ${GITHUB_TOKEN}
      - name: Push image to GitHub Packages
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/frigate-rpi:latest
